baseURL: 'https://martinez-c.github.io'
title: Flex Martin
languageCode: en-us
pygmentsCodeFences: true
enableRobotsTXT: true
theme: flex
publishDir: public
paginate: 5
summaryLength: 30
disableHugoGeneratorInject: true

outputs:
    home:
      - HTML
      - RSS
    page:
      - HTML
    section:
      - HTML
    term:
      - HTML
    taxonomy:
      - HTML

outputFormats:
    RSS:
      baseName: rss
      mediaType: application/rss+xml

permalinks:
  posts: '/:filename/'
  pages: '/:filename/'

markup:
  goldmark:
    renderer:
      unsafe: true
      enableInlineShortcodes: true

minify:
  tdewolff:
    html:
      keepQuotes: true
      keepWhitespace: false

params:
  logo: /img/logo.svg
  color: cadetblue #black
  width: 42rem
  #description: Generator hugo webpages
  footer: >-
    <p>Except where otherwise noted, content on this site is licensed under a
    a <a target="_blank" rel="nofollow" href="http://creativecommons.org/licenses/by/4.0/" rel="license">
    Creative Commons Attribution 4.0 International License</a>.</p>
  rss: >-
    To subscribe to this RSS feed, copy the address in the address bar and paste
    it into your favorite feed reader.
  divider: false #'\2015\2015' # Set to false to remove divider below posts on homepage
  schema: false
  opengraph: false
  twittercards: false
  summaries: true
  #utterances:
  #  repo:               # Set to Utterances repo URL to add Utterances comments
  #  issueterm: pathname
  #  theme: github-light
  netlify:
    honeypot: false     # Set to true to add honeypot field in contact form
    recaptcha: false    # Set to true to add recaptcha challenge in contact form
  # css:                # Uncomment to add custom CSS from a list of files
  #   - css/foo.css
  #   - bar.css
  # js:                 # Uncomment to add custom JS from a list of files
  #   - js/foo.js
  #   - bar.js



menu:
  nav:
    - name: Posts
      url: posts/
      weight: 1
    - name: Category
      url: categories/
      weight: 2
